import { pgTable, pgEnum, uuid, timestamp } from "drizzle-orm/pg-core";

/**
 * Cloud database schema (Drizzle / Supabase Postgres) — SERVER-ONLY.
 *
 * The entitlement source of truth. `profiles.id` equals the Supabase Auth user
 * id (auth.users.id), so a row is created per signed-up user. Free tier runs
 * fully on-device (ADR-002) and needs no row; a missing row is treated as free.
 *
 * Migrations are generated by drizzle-kit (see drizzle.config.ts) — never edit a
 * shipped migration. The matching SQL + RLS for Supabase lives in
 * docs/SETUP-supabase.md.
 */

export const entitlementEnum = pgEnum("entitlement", ["free", "pro", "lifetime"]);

export const profiles = pgTable("profiles", {
  id: uuid("id").primaryKey(),
  entitlement: entitlementEnum("entitlement").notNull().default("free"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type ProfileRow = typeof profiles.$inferSelect;
