import {
  boolean,
  integer,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Cloud database schema (Drizzle / Supabase Postgres) — SERVER-ONLY.
 *
 * The entitlement source of truth. `profiles.id` equals the Supabase Auth user
 * id (auth.users.id), so a row is created per signed-up user. Free tier runs
 * fully on-device (ADR-002) and needs no row; a missing row is treated as free.
 *
 * Migrations are generated by drizzle-kit (see drizzle.config.ts) — never edit a
 * shipped migration. The matching SQL + RLS for Supabase lives in
 * docs/SETUP-supabase.md.
 */

export const entitlementEnum = pgEnum("entitlement", ["free", "pro", "lifetime"]);

export const profiles = pgTable("profiles", {
  id: uuid("id").primaryKey(),
  entitlement: entitlementEnum("entitlement").notNull().default("free"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type ProfileRow = typeof profiles.$inferSelect;

/**
 * Connector OAuth tokens, encrypted at rest (story 3.4). One row per user and
 * provider. `ciphertext` is AES-256-GCM over the JSON token bundle (tag
 * appended); plaintext tokens never touch the database. RLS is enabled with no
 * client policies — only the server connection can read or write (SETUP-supabase.md).
 */
export const connectorTokens = pgTable(
  "connector_tokens",
  {
    userId: uuid("user_id").notNull(),
    provider: text("provider").notNull(),
    ciphertext: text("ciphertext").notNull(),
    iv: text("iv").notNull(),
    keyVersion: integer("key_version").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.provider] })],
);

/**
 * Server-side audit trail for access to sensitive records (Tier 3). Records who,
 * what kind of record and which action — never the record's contents.
 */
export const auditEvents = pgTable("audit_events", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull(),
  entity: text("entity").notNull(),
  action: text("action").notNull(),
  at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * RevenueCat webhook events (story 9.5). The event id makes delivery idempotent
 * (RevenueCat is at-least-once); `applied` + `event_at` keep out-of-order
 * events from undoing newer ones. user_id is null for anonymous app users.
 */
export const billingEvents = pgTable("billing_events", {
  eventId: text("event_id").primaryKey(),
  userId: uuid("user_id"),
  type: text("type").notNull(),
  eventAt: timestamp("event_at", { withTimezone: true }).notNull(),
  applied: boolean("applied").notNull().default(false),
  receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
});

export type ConnectorTokenRow = typeof connectorTokens.$inferSelect;
