// @otto/types — types derived from the Zod contracts via z.infer (CODING_CONVENTIONS §1).
// Never hand-maintain a type that duplicates a schema; re-export inferred types here.
export type {
  DayOfWeek,
  Recurrence,
  Money,
  RoutineAnchorKind,
  RoutineAnchor,
  RoutineMode,
  Routine,
  ReminderStatus,
  Reminder,
  Medication,
  Bill,
  IncomeCadence,
  Income,
  BudgetCategory,
  Transaction,
  DataSource,
  CalendarEvent,
  ContextItemKind,
  ContextItem,
  BriefingSlot,
  NudgeKind,
  Nudge,
  BriefingSource,
  Briefing,
  Consent,
  AuditAction,
  AuditActor,
  AuditEntry,
  SensitiveEntity,
} from "@otto/schemas";
